param ([switch]$Run, [string]$Arguments, [switch]$Sign, [string]$Thumbprint)

# ==============================================================================
# WINDOWS TOOLKIT // SHOGUN BUILD SYSTEM v7.3.1
# Builds the self-contained Ronin.ps1 GUI monolith from src\ and ui\ sources.
# Run Get-RoninSource.ps1 first if src/ files are missing.
# ==============================================================================

$BaseDir = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($BaseDir)) { $BaseDir = $PWD.Path }
$OutPath = Join-Path $BaseDir "Ronin.ps1"

if (Test-Path $OutPath) {
    try {
        Set-ItemProperty -Path $OutPath -Name IsReadOnly -Value $false -ErrorAction SilentlyContinue
        Remove-Item $OutPath -Force -ErrorAction Stop
    } catch {
        Write-Warning "[!] Could not remove existing Ronin.ps1: $($_.Exception.Message)"
        exit 1
    }
}

$SrcDir  = Join-Path $BaseDir "src"
$UIDir   = Join-Path $BaseDir "ui"

$CorePath = Join-Path $SrcDir "RoninCore.ps1"
$DBPath   = Join-Path $SrcDir "RoninDB.ps1"
$MainPath = Join-Path $SrcDir "Ronin.ps1"
$XamlPath = Join-Path $UIDir  "Ronin.xaml"

$missing = @()
foreach ($p in @($CorePath, $DBPath, $MainPath, $XamlPath)) {
    if (-not (Test-Path $p)) { $missing += $p }
}
if ($missing.Count -gt 0) {
    Write-Error "[!] BUILD FAILED - Missing source files:`n$($missing -join "`n")"
    Write-Host "`nRun Get-RoninSource.ps1 first to download the source files." -ForegroundColor Yellow
    exit 1
}

Write-Host "[*] Loading source files..." -ForegroundColor Cyan
Write-Progress -Activity "Windows Toolkit: Shogun Build" -Status "Loading Source Files..." -PercentComplete 10

$enc  = [System.Text.Encoding]::UTF8
$Core = [System.IO.File]::ReadAllText($CorePath, $enc)
$DB   = [System.IO.File]::ReadAllText($DBPath,   $enc)
$Main = [System.IO.File]::ReadAllText($MainPath,  $enc)
$Xaml = [System.IO.File]::ReadAllText($XamlPath,  $enc)

$Core = $Core -replace "`r`n", "`n"
$DB   = $DB   -replace "`r`n", "`n"
$Main = $Main -replace "`r`n", "`n"
$Xaml = $Xaml -replace "`r`n", "`n"
$Xaml = $Xaml.TrimStart([char]0xFEFF, [char]0xFFFD, [char]0x200B).Trim()

Write-Progress -Activity "Windows Toolkit: Shogun Build" -Status "Assembling Monolith..." -PercentComplete 40

$XamlLoadBlock = @'
    # Use .NET ReadAllText for bulletproof UTF-8 handling (auto-detects BOM, no PS quirks)
    try {
        $xamlContent = [System.IO.File]::ReadAllText($XamlPath, [System.Text.Encoding]::UTF8)
    } catch {
        $xamlContent = Get-Content $XamlPath -Raw -Encoding UTF8
    }
'@
$XamlLoadBlock = $XamlLoadBlock -replace "`r`n", "`n"

$XamlInlined = "    # MONOLITH: XAML inlined by BuildRonin.ps1`n    `$xamlContent = @'`n$Xaml`n'@"

if (-not $Main.Contains($XamlLoadBlock)) {
    Write-Error "[!] BUILD FAILED - Could not locate the XAML loader block in src\Ronin.ps1."
    exit 1
}
$Main = $Main.Replace($XamlLoadBlock, $XamlInlined)

$Main = $Main.Replace('if ($Missing.Count -gt 0) {', 'if ($false) {')
$Main = $Main.Replace('if ((Test-Path $CorePath) -and (Test-Path $DBPath)) {', 'if ($true) {')

$Main = $Main.Replace('. $CorePath', $Core)
$Main = $Main.Replace('. $DBPath',   $DB)

Write-Progress -Activity "Windows Toolkit: Shogun Build" -Status "Saving Monolith..." -PercentComplete 80

$Header = @"
# ==============================================================================
# WINDOWS TOOLKIT // SHOGUN EDITION v7.3.1 (DEFINITIVE MONOLITH)
# Built: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# DO NOT EDIT THIS FILE DIRECTLY - edit src\ and ui\ then rebuild
# ==============================================================================
"@

$FinalScript = "$Header`n$Main"

try {
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($OutPath, $FinalScript, $utf8NoBom)
} catch {
    try {
        $FinalScript | Set-Content -Path $OutPath -Encoding UTF8 -Force
    } catch {
        Write-Error "[!] BUILD FAILED - Cannot write output file: $($_.Exception.Message)"
        exit 1
    }
}

$built = [System.IO.File]::ReadAllText($OutPath, $enc)
$problems = @()
if (-not $built.Contains('<Window xmlns'))                      { $problems += "XAML did not inline" }
if ($built.Contains('[System.IO.File]::ReadAllText($XamlPath')) { $problems += "XAML loader stub still present" }
if ($built.Contains('. $CorePath'))                             { $problems += "RoninCore did not inline" }
if ($built.Contains('. $DBPath'))                               { $problems += "RoninDB did not inline" }
if (-not $built.Contains('Project Ronin Tweak Database'))       { $problems += "Tweak database missing" }
if ($problems.Count -gt 0) {
    Write-Error "[!] BUILD PRODUCED A BROKEN MONOLITH:`n  - $($problems -join "`n  - ")"
    Remove-Item $OutPath -Force -ErrorAction SilentlyContinue
    exit 1
}

Write-Progress -Activity "Windows Toolkit: Shogun Build" -Completed

$size = [Math]::Round((Get-Item $OutPath).Length / 1KB, 2)
Write-Host "[+] Build complete!" -ForegroundColor Cyan
Write-Host "    Output : $OutPath" -ForegroundColor White
Write-Host "    Size   : $size KB" -ForegroundColor White
Write-Host "    Built  : $(Get-Date -Format 'HH:mm:ss')" -ForegroundColor White
Write-Host "    Verify : self-contained monolith OK" -ForegroundColor Green

if ($Run) {
    Write-Host "[*] Launching..." -ForegroundColor Cyan
    & $OutPath $Arguments
}
